### ISSUE TITLE
The preference "Allow 1:1 zooming in with two double taps" does not zoom screenshots

### ISSUE THREAD

**Issue by vladrevers** [FossifyOrg/Gallery#40]
**Describe the bug**
After enabling the option in the settings, nothing happens when I double-click on an screenshot.

**To Reproduce**
1. Go to Gallery Settings
2. Enable on 'Allow 1:1 zooming in with two double taps'
3. Close settings and open any screenshot in gallery
4. Double click on screenshot
5. We can see that nothing is happening.

**Expected behavior**
If the size of the images matches the screen size, then the double-click behavior would be the same as if the option was disabled. Those. so that the first double click increases, the second decreases. Now nothing happens at all when you double or quadruple click.

<details>
  <summary>Screenshot</summary>

![Screenshot_20231231-184956](https://github.com/FossifyOrg/Gallery/assets/56305121/4ebc6a9d-dbfd-4e1d-bc3f-421c558dc226)
</details>

**Device info (please complete the following information):**
 - Model: Pixel 7
 - OS: Android 14
 - Version Gallery: 1.0.2

**Comment by Aga-C** [comment]
@vladrevers Are you sure that you are using version 1.0.2? Because it was fixed in this version.

**Comment by vladrevers** [comment]
> @vladrevers Are you sure that you are using version 1.0.2? Because it was fixed in this version.

I saw that this should be fixed, so I double-checked. Yes I am sure.
![Screenshot_20231231-192151](https://github.com/FossifyOrg/Gallery/assets/56305121/f3616596-6e12-460f-933c-69c182c3f0ea)

**Comment by vladrevers** [comment]
Now I checked again. In the photo with large extensions everything is fine. But for example, in screenshots (1080x2400) the problem remains.

**Comment by Aga-C** [comment]
It's a correct behavior, because it's already in 1:1. Simple Gallery worked in the same way. 

If you have this option turned on, first tap zooms the image so height or width matches (depending on orientation), next does 1:1 - on screenshots both conditions are always met.

If the option is turned off, double tap just does 2x zoom of what's currently on the screen, so it will always zoom.

**Comment by vladrevers** [comment]
@Aga-C Well, if you turn off this preference, the same screenshots will be enlarged. I would like it to be the same with this option enabled. Now nothing happens at all. Those.

**Comment by Aga-C** [comment]
Don't worry about the language, it's ok.

I agree, it can be misleading. Can you edit your opening post to include the information, that it happens only on screenshots (or generally images with the same resolution as the screen) and title to better tell the problem, like `The preference "Allow 1:1 zooming in with two double taps" does not zoom screenshots`?

**Comment by vladrevers** [comment]
@Aga-C okay, that's exactly what I was doing
